const MINIMUM_EVENT_DURATION = 1000 * 60 * 15; // 900000 milliseconds i.e. 15 Min

const ACTIVE = "ACTIVE";
const INACTIVE = "INACTIVE";
const ONGOING = "ONGOING";
const DONE = "DONE";

const EVENT_STATUSES = [ACTIVE, INACTIVE, ONGOING, DONE];
const NON_EDITABLE_STATUS = [ONGOING, DONE];

const SELFIE_SITE = "SELFIE_SITE";
const FESTIVAL_SITE = "FESTIVAL_SITE";
const BROADWAY_SITE = "BROADWAY_SITE";

const USER_TYPES = [SELFIE_SITE, FESTIVAL_SITE, BROADWAY_SITE];

module.exports = {
  MINIMUM_EVENT_DURATION,
  ACTIVE,
  INACTIVE,
  ONGOING,
  DONE,
  EVENT_STATUSES,
  SELFIE_SITE,
  FESTIVAL_SITE,
  BROADWAY_SITE,
  USER_TYPES,
  NON_EDITABLE_STATUS
};
